compiler:
    solc:
        remappings:
          - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.3.0"
          - "@openzeppelin-solc-0.7=OpenZeppelin/openzeppelin-contracts@3.1.0-solc-0.7"
          - "@uniswap/v3-periphery=Uniswap/v3-periphery@1.3.0"
          - "@uniswap/v3-core=Uniswap/v3-core@1.0.0"
dotenv: .env
